spring:
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  mail:
    host: smtp.163.com
    username: huangjiaqi041015@163.com
    password: GYeBE35YecRJHyj5
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/my-project
  Security:
    jwt:
      key: abcdefj
      expire: 7
  weather:
    key: c7df004f671d4e1fa1c7b1dfc26d4841
  minio:
    endpoint: http://localhost:9000
    username: admin
    password: admin123
server:
  servlet:
    encoding:
      force-response: true
