spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/my-project
  Security:
    jwt:
      key: abcdefj
      expire: 7
server:
  servlet:
    encoding:
      force-response: true
